[settings]
timeout = 1000

[relaychain.genesis.runtime.runtime_genesis_config.configuration.config]
  max_validators_per_core = 2
  needed_approvals = 2

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
chain_spec_command = "polkadot build-spec --chain rococo-local --disable-default-bootnode"
default_command = "polkadot"
  
  [[relaychain.nodes]]
  image = "{{MALUS_IMAGE}}"
  name = "alice"
  command = "malus dispute-ancestor"
  extra_args = [ "--alice", "-lparachain=debug" ]

  [[relaychain.nodes]]
  image = "{{MALUS_IMAGE}}"
  name = "bob"
  command = "malus dispute-ancestor"
  extra_args = [ "--bob", "-lparachain=debug"]
  
  [[relaychain.nodes]]
  image = "{{MALUS_IMAGE}}"
  name = "charlie"
  command = "malus dispute-ancestor"
  extra_args = [ "--charlie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  extra_args = [ "--dave", "-lparachain=debug"]

  [[relaychain.nodes]]
  name = "ferdie"
  extra_args = [ "--ferdie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "eve"
  extra_args = [ "--eve", "-lparachain=debug"]


[[parachains]]
id = 2000
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=1"

  [parachains.collator]
  image = "{{COL_IMAGE}}"
  name = "collator01"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--pvf-complexity=1", "--parachain-id=2000"]

[[parachains]]
id = 2001
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=2"

  [parachains.collator]
  image = "{{COL_IMAGE}}"
  name = "collator02"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--parachain-id=2001", "--pvf-complexity=2"]


[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"