[package]
name = "staking-miner"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
clap = { version = "3.0", features = ["derive", "env"] }
codec = { package = "parity-scale-codec", version = "2.0.0" }
tracing-subscriber = { version = "0.3.8", features = ["env-filter"]   }
jsonrpsee = { version = "0.8", features = ["ws-client", "macros"] }
log = "0.4.11"
paste = "1.0.6"
serde = "1.0.136"
serde_json = "1.0"
thiserror = "1.0.30"
tokio = { version = "1.16", features = ["macros", "rt-multi-thread", "sync"] }

remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }

frame-system = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }

core-primitives = { package = "polkadot-core-primitives", path = "../../core-primitives" }

runtime-common = { package = "polkadot-runtime-common", path = "../../runtime/common" }
polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { path = "../../runtime/kusama" }
westend-runtime = { path = "../../runtime/westend" }

sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }

[dev-dependencies]
sp-version = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
