[package]
name = "polkadot-voter-bags"
version = "0.9.17"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
clap = { version = "3.0", features = ["derive"] }

generate-bags = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "na-epm-pub" }

westend-runtime = { path = "../../runtime/westend" }
kusama-runtime = { path = "../../runtime/kusama" }
polkadot-runtime = { path = "../../runtime/polkadot" }
